services:
  openrouter-proxy-injector:
    image: ghcr.io/serjs/openrouter-proxy-injector
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:9999"
    volumes:
      - ./main.py:/app/main.py
    restart: unless-stopped
